name: Build package

on:
  push
  
env:
  BUILD_OUTPUT_PATH: $GITHUB_WORKSPACE/build_output

# Prevent running multiple-runners per workflow-file per event-name per branch per github-user (/ref)
# Ex. multiple changes are commited on the same PR/branch in a very short timespan,
#     cancel the previous runner (as it's not the latest anymore)
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  package_download:
    permissions:
      contents: write  
    runs-on: ubuntu-24.04
    steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - run: ./scripts/package-download.sh
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - run: mkdir -p ${{env.BUILD_OUTPUT_PATH}}
    
  qmake_with_cmd:
    needs: package_download
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - shell: cmd
        run: .\scripts\installer-build.bat
        
      - uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
           name: installer-artifact
           path: build_output/
      - name: Output artifact url
        run:  echo 'Artifact url is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
        
        


